### ISSUE TITLE
Transition Animation

### ISSUE THREAD

**Issue by yyYiran** [TeamMoodTrackerADY/MoodGuru#28]
Animated transition when 
- [x] click on a post on a dashboard to the detailed view
- [x] transition between different fragments (Dashboard, Compose, Chart)
- [x] transition between fragments -> activities and vice versa (ComposeActivity <-> Emotion Selection <-> Suggestion -> Dashboard)

(https://guides.codepath.com/android/shared-element-activity-transition)

**Comment by angelinale1104** [comment]
Done!
